# Site settings
title:       Weblog of a Machine Learner
email:       bayesian@machinelearner.me
author:      Kushal Khandelwal
description: "Daily Cribbing of a Chemist turned Machine Learner"
baseurl:     ""
url:         "http://weblog.kushalkhandelwal.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: kushal124
twitter_username: kushal124
google_plus_id: +KushalKhandelwal124
linkedin_username: 
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:  kramdown
permalink:    pretty
paginate:     3
sass:
compressed: true

kramdown:
	input: GFM
